### ISSUE TITLE
Include some documentation in the Readme, please

### ISSUE THREAD

**Issue by Yukitty** [Beliaar/godot-yaml-asset#1]
Hey. This asset on the Godot Asset Library does a terrible job of linking back to its source anywhere useful (probably their fault moreso than yours), and as such it took me nearly 20 minutes of scratching my head before I eventually found https://github.com/Beliaar/godot-yaml/blob/master/demo/Button.gd

Which seems to currently be the only documentation on how to properly use this at the moment?

I would very much appreciate if you would write clearly and explicitly that the functions are named "print" for output and "parse" for input (and any information on what happens in case of parsing errors) and link to the actual source repo somewhere in the little readme.md, please.

Thank you so much!

**Comment by Beliar83** [comment]
Heya, yes, you are right. I will look into adding that in the next days.

**Comment by Beliar83** [comment]
Closing for now, reopen if the current readme is not sufficient.
