### ISSUE TITLE
crash on invalid YAML syntax

### ISSUE THREAD

**Issue by Byteron** [Beliaar/godot-yaml-asset#2]
Hello there!
I have some weird behavior here. When I have a YAML file that contains a syntax error, godot just quits the process right on the start, without any kind of error message. 
When I use the debugger and set a break point to check if it loads the files, then yes, it loads all files and parses them until it hits the one with the invalid syntax. 
Invalid YAML:
```
attack:
  name staff
  damage: 3
  strikes: 2
```
call:
```
unc load_dir(path):
	var files = []
	files = get_files_in_directory(path, files)
	for file in files:
		var unit = yaml_parser.parse(file.get_as_text())
		print(unit.id)
```

I'm using Godot 3.0.6 on Linux

**Comment by Beliar83** [comment]
Heya thanks for reporting,

I found the problem and fixed it in the source repository. Once I have a fixed version on the asset library I will close this issue.

**Comment by Byteron** [comment]
Awesome, thank you!

**Comment by Beliar83** [comment]
I have uploaded the fix and submitted the changed download to the asset library, which is currently waiting for approval.
